name: LevelManager
main: com.littlegruz.levelmanager.LevelMain
version: 0.1

commands:
   spelllevel:
      description: Sets or changes level requirement for a spell
      usage: /spelllevel <spell_name> <spell_level>
   levelcap:
      description: Changes the max level a player can reach
      usage: /levelcap <level_cap>

permissions:
   manager.commands:
      description: Editing level requirements/caps
      default: op